import type { ScanResult, ScanOptions, Finding, Severity } from '../types.js'
import { scoreBand } from '../scoring/risk.js'
import { visibleFindings, countBySeverity, mcpFlags, recommendations } from './shared.js'

const BADGE: Record<Severity, string> = {
  critical: '🔴 Critical',
  high: '🟠 High',
  medium: '🟡 Medium',
  low: '🔵 Low',
  info: '⚪ Info',
}

function esc(s: string): string {
  return s.replace(/[|]/g, '\\|')
}

function section(lines: string[], title: string, findings: Finding[], home: string): void {
  if (findings.length === 0) return
  lines.push(`### ${title} (${findings.length})`)
  lines.push('')
  for (const f of findings) {
    lines.push(`- **${BADGE[f.severity]}** ${esc(f.title)}  `)
    lines.push(`  ${esc(f.detail)}${f.path ? ` \`${f.path.replace(home, '~')}\`` : ''}`)
  }
  lines.push('')
}

export function renderMarkdown(result: ScanResult, options: ScanOptions, home: string): string {
  const lines: string[] = []
  const date = new Date(result.scannedAt).toUTCString()
  const findings = visibleFindings(result, options.severity)
  const counts = countBySeverity(result.findings)

  lines.push('# snuf report')
  lines.push('')
  lines.push(`**Score:** ${result.score}/100 (${scoreBand(result.score)})  `)
  lines.push(`**Findings:** ${counts.critical} critical, ${counts.high} high, ${counts.medium} medium, ${counts.low} low  `)
  lines.push(`**Scanned:** ${date} on ${result.platform}, project \`${result.projectDir.replace(home, '~')}\`  `)
  lines.push(`**snuf:** v${result.version}, zero network calls, read only`)
  lines.push('')

  lines.push(`## Agents (${result.agents.length})`)
  lines.push('')
  if (result.agents.length === 0) {
    lines.push('No AI coding agents detected.')
  } else {
    lines.push('| Agent | Version | Running | Config |')
    lines.push('|---|---|---|---|')
    for (const a of result.agents) {
      lines.push(`| ${a.name} | ${a.version ?? ''} | ${a.running ? 'yes' : 'no'} | ${a.configPaths.map((p) => `\`${p.replace(home, '~')}\``).join('<br>')} |`)
    }
  }
  lines.push('')

  lines.push(`## MCP servers (${result.mcpServers.length})`)
  lines.push('')
  if (result.mcpServers.length === 0) {
    lines.push('No MCP servers configured.')
  } else {
    lines.push('| Server | Agent | Source | Runs | Flags |')
    lines.push('|---|---|---|---|---|')
    for (const s of result.mcpServers) {
      const runs = s.command ? `\`${esc([s.command, ...(s.args ?? [])].join(' ')).slice(0, 80)}\`` : s.url ? esc(s.url) : ''
      lines.push(`| ${esc(s.name)} | ${s.agent} | ${esc(s.source)} | ${runs} | ${mcpFlags(s).join(', ')} |`)
    }
  }
  lines.push('')

  lines.push(`## Findings (${findings.length})`)
  lines.push('')
  if (findings.length === 0) lines.push('No findings at the selected severity.')
  section(lines, 'Secrets', findings.filter((f) => f.category === 'secret'), home)
  section(lines, 'MCP servers', findings.filter((f) => f.category === 'mcp'), home)
  section(lines, 'Shell and permissions', findings.filter((f) => f.category === 'shell'), home)
  section(lines, 'File access', findings.filter((f) => f.category === 'file-access'), home)
  section(lines, 'Rules and skills', findings.filter((f) => f.category === 'rules'), home)

  lines.push('## Recommendations')
  lines.push('')
  recommendations(result).forEach((r, i) => lines.push(`${i + 1}. ${r}`))
  lines.push('')
  lines.push(`_Generated by [snuf](https://github.com/artmikula/snuf) v${result.version}._`)
  return lines.join('\n')
}
