import type { ScanResult, ScanOptions, Finding } from '../types.js'
import { scoreBand } from '../scoring/risk.js'

function severityBadge(severity: Finding['severity']): string {
  const map: Record<string, string> = {
    critical: '🔴 CRITICAL',
    high: '🟠 HIGH',
    medium: '🟡 MEDIUM',
    low: '🔵 LOW',
    info: '⚪ INFO',
  }
  return map[severity] ?? severity.toUpperCase()
}

function escapeMarkdown(s: string): string {
  return s.replace(/[|`]/g, '\\$&')
}

export function renderMarkdown(result: ScanResult, options: ScanOptions): string {
  const lines: string[] = []
  const date = new Date(result.scannedAt).toUTCString()

  lines.push('# snuf — AI Agent Security Report')
  lines.push('')
  lines.push(`**Score:** ${result.score}/100 — ${scoreBand(result.score)}`)
  lines.push(`**Scanned:** ${date}`)
  lines.push(`**Platform:** ${result.platform}`)
  lines.push('')
  lines.push('---')
  lines.push('')

  // Agents
  lines.push(`## Agents Found (${result.agents.length})`)
  lines.push('')
  if (result.agents.length === 0) {
    lines.push('_No AI agents detected._')
  } else {
    lines.push('| Agent | Version | Status | Config Paths |')
    lines.push('|-------|---------|--------|--------------|')
    for (const agent of result.agents) {
      const version = agent.version ?? '—'
      const status = agent.running ? '✅ running' : '○ not running'
      const paths = agent.configPaths.map((p) => `\`${escapeMarkdown(p)}\``).join(', ')
      lines.push(`| ${agent.name} | ${version} | ${status} | ${paths} |`)
    }
  }
  lines.push('')

  // MCP Servers
  lines.push(`## MCP Servers (${result.mcpServers.length})`)
  lines.push('')
  if (result.mcpServers.length === 0) {
    lines.push('_No MCP servers configured._')
  } else {
    lines.push('| Server | Source | Transport | Known | Shell | Network | Env Vars |')
    lines.push('|--------|--------|-----------|-------|-------|---------|----------|')
    for (const server of result.mcpServers) {
      const known = server.isKnown ? '✅' : '⚠️'
      const shell = server.hasShellAccess ? '⚠️ yes' : 'no'
      const network = server.hasNetworkAccess ? '⚠️ yes' : 'no'
      const envCount = server.envVars ? Object.keys(server.envVars).length : 0
      const envCell = envCount > 0 ? `⚠️ ${envCount} var${envCount > 1 ? 's' : ''}` : 'no'
      lines.push(
        `| \`${server.name}\` | ${server.source} | ${server.transport} | ${known} | ${shell} | ${network} | ${envCell} |`
      )
    }
  }
  lines.push('')

  // Findings
  const severityOrder: Finding['severity'][] = ['critical', 'high', 'medium', 'low', 'info']
  const minIdx = options.severity
    ? severityOrder.indexOf(options.severity as Finding['severity'])
    : severityOrder.length - 1
  const visibleFindings = result.findings.filter(
    (f) => severityOrder.indexOf(f.severity) <= minIdx
  )

  lines.push(`## Findings (${visibleFindings.length})`)
  lines.push('')
  if (visibleFindings.length === 0) {
    lines.push('_No findings for the selected severity threshold._')
  } else {
    // Group by severity
    for (const severity of severityOrder) {
      const group = visibleFindings.filter((f) => f.severity === severity)
      if (group.length === 0) continue
      lines.push(`### ${severityBadge(severity)} (${group.length})`)
      lines.push('')
      for (const finding of group) {
        lines.push(`#### ${escapeMarkdown(finding.title)}`)
        lines.push('')
        lines.push(`- **Category:** ${finding.category}`)
        if (finding.agent) lines.push(`- **Agent:** ${finding.agent}`)
        if (finding.path) lines.push(`- **Path:** \`${escapeMarkdown(finding.path)}\``)
        lines.push(`- **Detail:** ${escapeMarkdown(finding.detail)}`)
        lines.push('')
      }
    }
  }

  // Recommendations
  lines.push('## Recommendations')
  lines.push('')
  const criticalAndHigh = result.findings.filter(
    (f) => f.severity === 'critical' || f.severity === 'high'
  )
  if (criticalAndHigh.length > 0) {
    lines.push(`1. **Immediate action required:** ${criticalAndHigh.length} critical/high finding(s) need attention`)
  }
  const mcpWithEnv = result.mcpServers.filter(
    (s) => s.envVars && Object.keys(s.envVars).length > 0
  )
  if (mcpWithEnv.length > 0) {
    lines.push('2. Move API keys from MCP configs to a proper secrets manager')
  }
  const unknownMcp = result.mcpServers.filter((s) => !s.isKnown)
  if (unknownMcp.length > 0) {
    lines.push(`3. Audit unknown MCP servers: ${unknownMcp.map((s) => s.name).join(', ')}`)
  }
  lines.push('')
  lines.push('---')
  lines.push('')
  lines.push(`_Generated by [snuf](https://github.com/artmikula/snuf) on ${date}_`)

  return lines.join('\n')
}
